write new derivation in pkgs for worktrunk https://github.com/max-sixty/worktrunk
Error: nu::parser::assignment_requires_mutable_variable

  × Assignment to an immutable variable.
    ╭─[/home/knoopx/.nix/modules/home-manager/programs/vicinae/scripts/screen-recording.nu:28:5]
 27 │     let index = ($names | enumerate | where item == $selected | get index | first)
 28 │     $output = ($outputs | get $index)
    ·     ───┬───
    ·        ╰── needs to be a mutable variable
 29 │ } else {
    ╰────
  help: declare the variable with `mut`, or shadow it again with `let`